import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'

import clsx from 'clsx'

import AuthProvider from '@/components/providers/authProvider'

import Header from './header'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={clsx(
					'bg-honeydew min-h-screen min-w-[1028px] p-10',
					inter.className
				)}
			>
				<AuthProvider>
					<Header />
					{children}
					<Footer />
				</AuthProvider>
			</body>
		</html>
	)
}
