export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function CheckoutLayout({
	children
}: {
	children: React.ReactNode
}) {
	return <section>{children}</section>
}
